/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vamosaturistear.Sitios;

import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class AgregarSitiosFrame extends javax.swing.JFrame {

    /**
     * Creates new form AgregarSitiosFrame
     */
    
    public AgregarSitiosFrame() {
        initComponents();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new com.vamosaturistear.TextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtMovil = new com.vamosaturistear.TextField();
        txtFijo = new com.vamosaturistear.TextField();
        cmbAcce = new javax.swing.JComboBox<>();
        cmbClima = new javax.swing.JComboBox<>();
        cmbParqueo = new javax.swing.JComboBox<>();
        cmbMascotas = new javax.swing.JComboBox<>();
        cmbVehiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProvincia = new com.vamosaturistear.TextField();
        txtDistrito = new com.vamosaturistear.TextField();
        txtCanton = new com.vamosaturistear.TextField();
        txtCPostal = new com.vamosaturistear.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtComida = new com.vamosaturistear.TextField();
        txtHospedaje = new com.vamosaturistear.TextField();
        txtExtras = new com.vamosaturistear.TextField();
        txtTotal = new com.vamosaturistear.TextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRecomendaciones = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtSitio = new com.vamosaturistear.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 41, 45));

        jPanel1.setBackground(new java.awt.Color(36, 41, 45));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Sitio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        txtNombre.setBackground(new java.awt.Color(49, 53, 57));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setLabelText("Nombre");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 158, 45));

        cmbCategoria.setBackground(new java.awt.Color(49, 53, 57));
        cmbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria ", "Hotel", "Cabaña", "Playa", "Montaña/Volcan", "Catarata" }));
        cmbCategoria.setBorder(null);
        cmbCategoria.setLightWeightPopupEnabled(false);
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 158, 45));

        txtMovil.setBackground(new java.awt.Color(49, 53, 57));
        txtMovil.setForeground(new java.awt.Color(255, 255, 255));
        txtMovil.setLabelText("Telefono Movil");
        jPanel1.add(txtMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 158, 45));

        txtFijo.setBackground(new java.awt.Color(49, 53, 57));
        txtFijo.setForeground(new java.awt.Color(255, 255, 255));
        txtFijo.setLabelText("Telefono Fijo");
        jPanel1.add(txtFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 158, -1));

        cmbAcce.setBackground(new java.awt.Color(49, 53, 57));
        cmbAcce.setForeground(new java.awt.Color(255, 255, 255));
        cmbAcce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accesibilidad", "Todo Publico", "No Discapacitados", "Otro" }));
        jPanel1.add(cmbAcce, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 158, 45));

        cmbClima.setBackground(new java.awt.Color(49, 53, 57));
        cmbClima.setForeground(new java.awt.Color(255, 255, 255));
        cmbClima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clima", "Lluvioso", "Tropical", "Seco", "Ventoso", " ", " " }));
        jPanel1.add(cmbClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 158, 45));

        cmbParqueo.setBackground(new java.awt.Color(49, 53, 57));
        cmbParqueo.setForeground(new java.awt.Color(255, 255, 255));
        cmbParqueo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parqueo", "Si", "No" }));
        jPanel1.add(cmbParqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 158, 45));

        cmbMascotas.setBackground(new java.awt.Color(49, 53, 57));
        cmbMascotas.setForeground(new java.awt.Color(255, 255, 255));
        cmbMascotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mascotas", "Si", "No" }));
        jPanel1.add(cmbMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 158, 45));

        cmbVehiculo.setBackground(new java.awt.Color(49, 53, 57));
        cmbVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehiculo", "Todo tipo", "4x2", "Alto" }));
        cmbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 158, 45));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalles Basicos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        txtProvincia.setBackground(new java.awt.Color(49, 53, 57));
        txtProvincia.setForeground(new java.awt.Color(255, 255, 255));
        txtProvincia.setLabelText("Provincia");
        jPanel1.add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 158, 45));

        txtDistrito.setBackground(new java.awt.Color(49, 53, 57));
        txtDistrito.setForeground(new java.awt.Color(255, 255, 255));
        txtDistrito.setLabelText("Distrito");
        jPanel1.add(txtDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 158, 45));

        txtCanton.setBackground(new java.awt.Color(49, 53, 57));
        txtCanton.setForeground(new java.awt.Color(255, 255, 255));
        txtCanton.setLabelText("Canton");
        jPanel1.add(txtCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 158, 45));

        txtCPostal.setBackground(new java.awt.Color(49, 53, 57));
        txtCPostal.setForeground(new java.awt.Color(255, 255, 255));
        txtCPostal.setLabelText("Codigo Postal");
        jPanel1.add(txtCPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 158, 45));

        txtDireccion.setBackground(new java.awt.Color(49, 53, 57));
        txtDireccion.setColumns(20);
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setRows(6);
        txtDireccion.setMinimumSize(new java.awt.Dimension(180, 200));
        jScrollPane2.setViewportView(txtDireccion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 334, 110));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        txtComida.setBackground(new java.awt.Color(49, 53, 57));
        txtComida.setForeground(new java.awt.Color(255, 255, 255));
        txtComida.setLabelText("Comida");
        txtComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComidaActionPerformed(evt);
            }
        });
        jPanel1.add(txtComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 158, 45));

        txtHospedaje.setBackground(new java.awt.Color(49, 53, 57));
        txtHospedaje.setForeground(new java.awt.Color(255, 255, 255));
        txtHospedaje.setLabelText("Hospedaje");
        jPanel1.add(txtHospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 158, 45));

        txtExtras.setBackground(new java.awt.Color(49, 53, 57));
        txtExtras.setForeground(new java.awt.Color(255, 255, 255));
        txtExtras.setLabelText("Extras");
        jPanel1.add(txtExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 158, 45));

        txtTotal.setBackground(new java.awt.Color(49, 53, 57));
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setLabelText("Total Estimado");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 158, 45));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recomendaciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        txtRecomendaciones.setBackground(new java.awt.Color(49, 53, 57));
        txtRecomendaciones.setColumns(20);
        txtRecomendaciones.setForeground(new java.awt.Color(255, 255, 255));
        txtRecomendaciones.setRows(5);
        jScrollPane1.setViewportView(txtRecomendaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 334, 108));

        jButton1.setBackground(new java.awt.Color(49, 53, 57));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 100, 30));

        jButton2.setBackground(new java.awt.Color(49, 53, 57));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 100, 30));

        jButton3.setBackground(new java.awt.Color(49, 53, 57));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 100, 30));

        jButton4.setBackground(new java.awt.Color(49, 53, 57));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Eliminar");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 100, 30));

        txtSitio.setBackground(new java.awt.Color(49, 53, 57));
        txtSitio.setForeground(new java.awt.Color(255, 255, 255));
        txtSitio.setLabelText("Sitio");
        jPanel1.add(txtSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 158, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVehiculoActionPerformed

    private void txtComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbClases.Sitios objSitios= new dbClases.Sitios();
        objSitios.guardarDatos(txtNombre, cmbCategoria, txtMovil, txtFijo, 
                cmbAcce,cmbClima,  cmbParqueo,  cmbMascotas, cmbVehiculo,  
                txtRecomendaciones,  txtProvincia, txtCanton,  txtDistrito,  
                txtCPostal,  txtDireccion, txtSitio, txtComida,  txtHospedaje,  txtExtras,  
                txtTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarSitiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarSitiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarSitiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarSitiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarSitiosFrame().setVisible(true);
            }
        });
        
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAcce;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbClima;
    private javax.swing.JComboBox<String> cmbMascotas;
    private javax.swing.JComboBox<String> cmbParqueo;
    private javax.swing.JComboBox<String> cmbVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.vamosaturistear.TextField txtCPostal;
    private com.vamosaturistear.TextField txtCanton;
    private com.vamosaturistear.TextField txtComida;
    private javax.swing.JTextArea txtDireccion;
    private com.vamosaturistear.TextField txtDistrito;
    private com.vamosaturistear.TextField txtExtras;
    private com.vamosaturistear.TextField txtFijo;
    private com.vamosaturistear.TextField txtHospedaje;
    private com.vamosaturistear.TextField txtMovil;
    private com.vamosaturistear.TextField txtNombre;
    private com.vamosaturistear.TextField txtProvincia;
    private javax.swing.JTextArea txtRecomendaciones;
    private com.vamosaturistear.TextField txtSitio;
    private com.vamosaturistear.TextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
